// GENERATED FIXTURES. Do not edit by hand.
//
// Captured verbatim from @palembang/core (packages/core), the released
// JavaScript SDK, via renderPalembangSvg(options) for the same option shapes
// PalembangKit's Palembang.renderSVG supports. These are cross-renderer
// parity fixtures (docs/specification.md section 12): if PalembangKit's
// output ever stops matching one of these strings byte-for-byte, either
// PalembangKit or the JS renderer has drifted from the shared contract in
// implementations/svg/render.py and implementations/web/palembang.js.
//
// Regenerate by re-running the fixture capture described in
// packages/swift/README.md against the current packages/core release.
//
// IMPORTANT — trailing newline: @palembang/core's renderPalembangSvg (and
// Renderer.renderSVG in this package) always terminate the SVG with a
// final "</svg>\n". Swift multiline string literals ("""..."""), however,
// do NOT include the line break immediately before the closing """
// delimiter — so a literal whose last content line is "</svg>" silently
// yields a string with no trailing LF. Each fixture below therefore ends
// its multiline literal one line early and appends the dropped LF back
// explicitly with + "\n", rather than relying on an easy-to-miss blank
// line before the closing """. Do not "simplify" this back to a bare
// multiline literal — that reintroduces the missing-LF bug.

import XCTest
@testable import PalembangKit

final class ParityTests: XCTestCase {

    func testCanonicalWide() throws {
        let expected = """
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="1920" height="1080" viewBox="0 0 1920 1080">
  <title>Palembang Graphic System</title>
  <desc>Canonical normalized SVG renderer; haze middle-stop alpha 0.800000011920929</desc>
  <metadata>Palembang Graphic System — ybtiger107. https://github.com/ybtiger107/palembang-graphic-system — CC BY 4.0. Generated by the Palembang renderer; see VISUAL-LICENSE.md for scope.</metadata>
  <defs>
    <radialGradient id="sky" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.21929825360599572 -1.9281435999527672 0.9415203344570438 -0.4491017437820297 0.24853804688462697 2.188622625960173)">
      <stop offset="0" stop-color="#DF8117" stop-opacity="1"/>
      <stop offset="1" stop-color="#8198C4" stop-opacity="1"/>
    </radialGradient>
    <radialGradient id="sea-base" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.8099414028954617 -1.8862273661495264 1.8862273661495264 -3.396822741494832 0.3668277375468474 3.6115849804896354)">
      <stop offset="0" stop-color="#8BA08A" stop-opacity="1"/>
      <stop offset="1" stop-color="#516872" stop-opacity="1"/>
    </radialGradient>
    <linearGradient id="sea-haze" gradientUnits="objectBoundingBox" x1="0" y1="0.5" x2="1" y2="0.5" gradientTransform="matrix(-1.5287276299123954e-16 -2.346874889622273 2.346874889622273 -1.6816003929036348e-15 -0.7843749551931998 1.2312499497289566)">
      <stop offset="0.20000000298023224" stop-color="#C0C0C0" stop-opacity="0"/>
      <stop offset="0.30000001192092896" stop-color="#C0C0C0" stop-opacity="0.800000011920929"/>
      <stop offset="0.3764832615852356" stop-color="#C0C0C0" stop-opacity="0"/>
    </linearGradient>
    <radialGradient id="sea-glow" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(0.3093751112907292 -1.106250001837 1.106250001837 1.2375004451629168 -0.43281258818896307 0.8249997838079705)">
      <stop offset="0.09071040898561478" stop-color="#78B6BA" stop-opacity="1"/>
      <stop offset="1" stop-color="#78B6BA" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect id="sky-field" x="0" y="0" width="1920" height="540" fill="url(#sky)" opacity="1"/>
  <rect id="sea-base-field" x="0" y="540" width="1920" height="540" fill="url(#sea-base)" opacity="1"/>
  <rect id="sea-haze-field" x="0" y="540" width="1920" height="540" fill="url(#sea-haze)" opacity="0.44999998807907104"/>
  <rect id="sea-glow-field" x="0" y="540" width="1920" height="540" fill="url(#sea-glow)" opacity="0.6000000238418579"/>
</svg>
""" + "\n"
        XCTAssertEqual(try Palembang.renderSVG(width: 1920, height: 1080), expected)
    }

    func testSquare() throws {
        let expected = """
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="1000" height="1000" viewBox="0 0 1000 1000">
  <title>Palembang Graphic System</title>
  <desc>Canonical normalized SVG renderer; haze middle-stop alpha 0.800000011920929</desc>
  <metadata>Palembang Graphic System — ybtiger107. https://github.com/ybtiger107/palembang-graphic-system — CC BY 4.0. Generated by the Palembang renderer; see VISUAL-LICENSE.md for scope.</metadata>
  <defs>
    <radialGradient id="sky" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.21929825360599572 -1.9281435999527672 0.9415203344570438 -0.4491017437820297 0.24853804688462697 2.188622625960173)">
      <stop offset="0" stop-color="#DF8117" stop-opacity="1"/>
      <stop offset="1" stop-color="#8198C4" stop-opacity="1"/>
    </radialGradient>
    <radialGradient id="sea-base" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.8099414028954617 -1.8862273661495264 1.8862273661495264 -3.396822741494832 0.3668277375468474 3.6115849804896354)">
      <stop offset="0" stop-color="#8BA08A" stop-opacity="1"/>
      <stop offset="1" stop-color="#516872" stop-opacity="1"/>
    </radialGradient>
    <linearGradient id="sea-haze" gradientUnits="objectBoundingBox" x1="0" y1="0.5" x2="1" y2="0.5" gradientTransform="matrix(-1.5287276299123954e-16 -2.346874889622273 2.346874889622273 -1.6816003929036348e-15 -0.7843749551931998 1.2312499497289566)">
      <stop offset="0.20000000298023224" stop-color="#C0C0C0" stop-opacity="0"/>
      <stop offset="0.30000001192092896" stop-color="#C0C0C0" stop-opacity="0.800000011920929"/>
      <stop offset="0.3764832615852356" stop-color="#C0C0C0" stop-opacity="0"/>
    </linearGradient>
    <radialGradient id="sea-glow" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(0.3093751112907292 -1.106250001837 1.106250001837 1.2375004451629168 -0.43281258818896307 0.8249997838079705)">
      <stop offset="0.09071040898561478" stop-color="#78B6BA" stop-opacity="1"/>
      <stop offset="1" stop-color="#78B6BA" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect id="sky-field" x="0" y="0" width="1000" height="500" fill="url(#sky)" opacity="1"/>
  <rect id="sea-base-field" x="0" y="500" width="1000" height="500" fill="url(#sea-base)" opacity="1"/>
  <rect id="sea-haze-field" x="0" y="500" width="1000" height="500" fill="url(#sea-haze)" opacity="0.44999998807907104"/>
  <rect id="sea-glow-field" x="0" y="500" width="1000" height="500" fill="url(#sea-glow)" opacity="0.6000000238418579"/>
</svg>
""" + "\n"
        XCTAssertEqual(try Palembang.renderSVG(width: 1000, height: 1000), expected)
    }

    func testSmall320() throws {
        let expected = """
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="320" height="320" viewBox="0 0 320 320">
  <title>Palembang Graphic System</title>
  <desc>Canonical normalized SVG renderer; haze middle-stop alpha 1</desc>
  <metadata>Palembang Graphic System — ybtiger107. https://github.com/ybtiger107/palembang-graphic-system — CC BY 4.0. Generated by the Palembang renderer; see VISUAL-LICENSE.md for scope.</metadata>
  <defs>
    <radialGradient id="sky" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.21929825360599572 -1.9281435999527672 0.9415203344570438 -0.4491017437820297 0.24853804688462697 2.188622625960173)">
      <stop offset="0" stop-color="#DF8117" stop-opacity="1"/>
      <stop offset="1" stop-color="#8198C4" stop-opacity="1"/>
    </radialGradient>
    <radialGradient id="sea-base" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.8099414028954617 -1.8862273661495264 1.8862273661495264 -3.396822741494832 0.3668277375468474 3.6115849804896354)">
      <stop offset="0" stop-color="#8BA08A" stop-opacity="1"/>
      <stop offset="1" stop-color="#516872" stop-opacity="1"/>
    </radialGradient>
    <linearGradient id="sea-haze" gradientUnits="objectBoundingBox" x1="0" y1="0.5" x2="1" y2="0.5" gradientTransform="matrix(-1.5287276299123954e-16 -2.346874889622273 2.346874889622273 -1.6816003929036348e-15 -0.7843749551931998 1.2312499497289566)">
      <stop offset="0.20000000298023224" stop-color="#C0C0C0" stop-opacity="0"/>
      <stop offset="0.30000001192092896" stop-color="#C0C0C0" stop-opacity="1"/>
      <stop offset="0.3764832615852356" stop-color="#C0C0C0" stop-opacity="0"/>
    </linearGradient>
    <radialGradient id="sea-glow" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(0.3093751112907292 -1.106250001837 1.106250001837 1.2375004451629168 -0.43281258818896307 0.8249997838079705)">
      <stop offset="0.09071040898561478" stop-color="#78B6BA" stop-opacity="1"/>
      <stop offset="1" stop-color="#78B6BA" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect id="sky-field" x="0" y="0" width="320" height="160" fill="url(#sky)" opacity="1"/>
  <rect id="sea-base-field" x="0" y="160" width="320" height="160" fill="url(#sea-base)" opacity="1"/>
  <rect id="sea-haze-field" x="0" y="160" width="320" height="160" fill="url(#sea-haze)" opacity="0.44999998807907104"/>
  <rect id="sea-glow-field" x="0" y="160" width="320" height="160" fill="url(#sea-glow)" opacity="0.6000000238418579"/>
</svg>
""" + "\n"
        XCTAssertEqual(try Palembang.renderSVG(width: 320, height: 320), expected)
    }

    func testCustomAspect() throws {
        let expected = """
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="833" height="577" viewBox="0 0 833 577">
  <title>Palembang Graphic System</title>
  <desc>Canonical normalized SVG renderer; haze middle-stop alpha 0.800000011920929</desc>
  <metadata>Palembang Graphic System — ybtiger107. https://github.com/ybtiger107/palembang-graphic-system — CC BY 4.0. Generated by the Palembang renderer; see VISUAL-LICENSE.md for scope.</metadata>
  <defs>
    <radialGradient id="sky" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.21929825360599572 -1.9281435999527672 0.9415203344570438 -0.4491017437820297 0.24853804688462697 2.188622625960173)">
      <stop offset="0" stop-color="#DF8117" stop-opacity="1"/>
      <stop offset="1" stop-color="#8198C4" stop-opacity="1"/>
    </radialGradient>
    <radialGradient id="sea-base" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.8099414028954617 -1.8862273661495264 1.8862273661495264 -3.396822741494832 0.3668277375468474 3.6115849804896354)">
      <stop offset="0" stop-color="#8BA08A" stop-opacity="1"/>
      <stop offset="1" stop-color="#516872" stop-opacity="1"/>
    </radialGradient>
    <linearGradient id="sea-haze" gradientUnits="objectBoundingBox" x1="0" y1="0.5" x2="1" y2="0.5" gradientTransform="matrix(-1.5287276299123954e-16 -2.346874889622273 2.346874889622273 -1.6816003929036348e-15 -0.7843749551931998 1.2312499497289566)">
      <stop offset="0.20000000298023224" stop-color="#C0C0C0" stop-opacity="0"/>
      <stop offset="0.30000001192092896" stop-color="#C0C0C0" stop-opacity="0.800000011920929"/>
      <stop offset="0.3764832615852356" stop-color="#C0C0C0" stop-opacity="0"/>
    </linearGradient>
    <radialGradient id="sea-glow" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(0.3093751112907292 -1.106250001837 1.106250001837 1.2375004451629168 -0.43281258818896307 0.8249997838079705)">
      <stop offset="0.09071040898561478" stop-color="#78B6BA" stop-opacity="1"/>
      <stop offset="1" stop-color="#78B6BA" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect id="sky-field" x="0" y="0" width="833" height="288.5" fill="url(#sky)" opacity="1"/>
  <rect id="sea-base-field" x="0" y="288.5" width="833" height="288.5" fill="url(#sea-base)" opacity="1"/>
  <rect id="sea-haze-field" x="0" y="288.5" width="833" height="288.5" fill="url(#sea-haze)" opacity="0.44999998807907104"/>
  <rect id="sea-glow-field" x="0" y="288.5" width="833" height="288.5" fill="url(#sea-glow)" opacity="0.6000000238418579"/>
</svg>
""" + "\n"
        XCTAssertEqual(try Palembang.renderSVG(width: 833, height: 577), expected)
    }

    func testPartialPaletteOverride() throws {
        let expected = """
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="1920" height="1080" viewBox="0 0 1920 1080">
  <title>Palembang Graphic System</title>
  <desc>Canonical normalized SVG renderer; haze middle-stop alpha 0.800000011920929</desc>
  <metadata>Palembang Graphic System — ybtiger107. https://github.com/ybtiger107/palembang-graphic-system — CC BY 4.0. Generated by the Palembang renderer; see VISUAL-LICENSE.md for scope.</metadata>
  <defs>
    <radialGradient id="sky" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.21929825360599572 -1.9281435999527672 0.9415203344570438 -0.4491017437820297 0.24853804688462697 2.188622625960173)">
      <stop offset="0" stop-color="#D97706" stop-opacity="1"/>
      <stop offset="1" stop-color="#8198C4" stop-opacity="1"/>
    </radialGradient>
    <radialGradient id="sea-base" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.8099414028954617 -1.8862273661495264 1.8862273661495264 -3.396822741494832 0.3668277375468474 3.6115849804896354)">
      <stop offset="0" stop-color="#8BA08A" stop-opacity="1"/>
      <stop offset="1" stop-color="#516872" stop-opacity="1"/>
    </radialGradient>
    <linearGradient id="sea-haze" gradientUnits="objectBoundingBox" x1="0" y1="0.5" x2="1" y2="0.5" gradientTransform="matrix(-1.5287276299123954e-16 -2.346874889622273 2.346874889622273 -1.6816003929036348e-15 -0.7843749551931998 1.2312499497289566)">
      <stop offset="0.20000000298023224" stop-color="#C0C0C0" stop-opacity="0"/>
      <stop offset="0.30000001192092896" stop-color="#C0C0C0" stop-opacity="0.800000011920929"/>
      <stop offset="0.3764832615852356" stop-color="#C0C0C0" stop-opacity="0"/>
    </linearGradient>
    <radialGradient id="sea-glow" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(0.3093751112907292 -1.106250001837 1.106250001837 1.2375004451629168 -0.43281258818896307 0.8249997838079705)">
      <stop offset="0.09071040898561478" stop-color="#78B6BA" stop-opacity="1"/>
      <stop offset="1" stop-color="#78B6BA" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect id="sky-field" x="0" y="0" width="1920" height="540" fill="url(#sky)" opacity="1"/>
  <rect id="sea-base-field" x="0" y="540" width="1920" height="540" fill="url(#sea-base)" opacity="1"/>
  <rect id="sea-haze-field" x="0" y="540" width="1920" height="540" fill="url(#sea-haze)" opacity="0.44999998807907104"/>
  <rect id="sea-glow-field" x="0" y="540" width="1920" height="540" fill="url(#sea-glow)" opacity="0.6000000238418579"/>
</svg>
""" + "\n"
        XCTAssertEqual(try Palembang.renderSVG(width: 1920, height: 1080, palette: [.skyHot: "#D97706"]), expected)
    }

    func testMultiplePaletteOverrides() throws {
        let expected = """
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="1600" height="900" viewBox="0 0 1600 900">
  <title>Palembang Graphic System</title>
  <desc>Canonical normalized SVG renderer; haze middle-stop alpha 0.800000011920929</desc>
  <metadata>Palembang Graphic System — ybtiger107. https://github.com/ybtiger107/palembang-graphic-system — CC BY 4.0. Generated by the Palembang renderer; see VISUAL-LICENSE.md for scope.</metadata>
  <defs>
    <radialGradient id="sky" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.21929825360599572 -1.9281435999527672 0.9415203344570438 -0.4491017437820297 0.24853804688462697 2.188622625960173)">
      <stop offset="0" stop-color="#D97706" stop-opacity="1"/>
      <stop offset="1" stop-color="#8198C4" stop-opacity="1"/>
    </radialGradient>
    <radialGradient id="sea-base" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.8099414028954617 -1.8862273661495264 1.8862273661495264 -3.396822741494832 0.3668277375468474 3.6115849804896354)">
      <stop offset="0" stop-color="#8BA08A" stop-opacity="1"/>
      <stop offset="1" stop-color="#516872" stop-opacity="1"/>
    </radialGradient>
    <linearGradient id="sea-haze" gradientUnits="objectBoundingBox" x1="0" y1="0.5" x2="1" y2="0.5" gradientTransform="matrix(-1.5287276299123954e-16 -2.346874889622273 2.346874889622273 -1.6816003929036348e-15 -0.7843749551931998 1.2312499497289566)">
      <stop offset="0.20000000298023224" stop-color="#C0C0C0" stop-opacity="0"/>
      <stop offset="0.30000001192092896" stop-color="#C0C0C0" stop-opacity="0.800000011920929"/>
      <stop offset="0.3764832615852356" stop-color="#C0C0C0" stop-opacity="0"/>
    </linearGradient>
    <radialGradient id="sea-glow" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(0.3093751112907292 -1.106250001837 1.106250001837 1.2375004451629168 -0.43281258818896307 0.8249997838079705)">
      <stop offset="0.09071040898561478" stop-color="#22D3EE" stop-opacity="1"/>
      <stop offset="1" stop-color="#22D3EE" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect id="sky-field" x="0" y="0" width="1600" height="450" fill="url(#sky)" opacity="1"/>
  <rect id="sea-base-field" x="0" y="450" width="1600" height="450" fill="url(#sea-base)" opacity="1"/>
  <rect id="sea-haze-field" x="0" y="450" width="1600" height="450" fill="url(#sea-haze)" opacity="0.44999998807907104"/>
  <rect id="sea-glow-field" x="0" y="450" width="1600" height="450" fill="url(#sea-glow)" opacity="0.6000000238418579"/>
</svg>
""" + "\n"
        XCTAssertEqual(try Palembang.renderSVG(width: 1600, height: 900, palette: [.skyHot: "#D97706", .seaGlow: "#22D3EE"]), expected)
    }

    func testAttributionOff() throws {
        let expected = """
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="1920" height="1080" viewBox="0 0 1920 1080">
  <title>Palembang Graphic System</title>
  <desc>Canonical normalized SVG renderer; haze middle-stop alpha 0.800000011920929</desc>
  <defs>
    <radialGradient id="sky" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.21929825360599572 -1.9281435999527672 0.9415203344570438 -0.4491017437820297 0.24853804688462697 2.188622625960173)">
      <stop offset="0" stop-color="#DF8117" stop-opacity="1"/>
      <stop offset="1" stop-color="#8198C4" stop-opacity="1"/>
    </radialGradient>
    <radialGradient id="sea-base" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.8099414028954617 -1.8862273661495264 1.8862273661495264 -3.396822741494832 0.3668277375468474 3.6115849804896354)">
      <stop offset="0" stop-color="#8BA08A" stop-opacity="1"/>
      <stop offset="1" stop-color="#516872" stop-opacity="1"/>
    </radialGradient>
    <linearGradient id="sea-haze" gradientUnits="objectBoundingBox" x1="0" y1="0.5" x2="1" y2="0.5" gradientTransform="matrix(-1.5287276299123954e-16 -2.346874889622273 2.346874889622273 -1.6816003929036348e-15 -0.7843749551931998 1.2312499497289566)">
      <stop offset="0.20000000298023224" stop-color="#C0C0C0" stop-opacity="0"/>
      <stop offset="0.30000001192092896" stop-color="#C0C0C0" stop-opacity="0.800000011920929"/>
      <stop offset="0.3764832615852356" stop-color="#C0C0C0" stop-opacity="0"/>
    </linearGradient>
    <radialGradient id="sea-glow" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(0.3093751112907292 -1.106250001837 1.106250001837 1.2375004451629168 -0.43281258818896307 0.8249997838079705)">
      <stop offset="0.09071040898561478" stop-color="#78B6BA" stop-opacity="1"/>
      <stop offset="1" stop-color="#78B6BA" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect id="sky-field" x="0" y="0" width="1920" height="540" fill="url(#sky)" opacity="1"/>
  <rect id="sea-base-field" x="0" y="540" width="1920" height="540" fill="url(#sea-base)" opacity="1"/>
  <rect id="sea-haze-field" x="0" y="540" width="1920" height="540" fill="url(#sea-haze)" opacity="0.44999998807907104"/>
  <rect id="sea-glow-field" x="0" y="540" width="1920" height="540" fill="url(#sea-glow)" opacity="0.6000000238418579"/>
</svg>
""" + "\n"
        XCTAssertEqual(try Palembang.renderSVG(width: 1920, height: 1080, attribution: false), expected)
    }

    func testExplicitHazeAlpha640() throws {
        let expected = """
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="640" height="480" viewBox="0 0 640 480">
  <title>Palembang Graphic System</title>
  <desc>Canonical normalized SVG renderer; haze middle-stop alpha 0.8</desc>
  <metadata>Palembang Graphic System — ybtiger107. https://github.com/ybtiger107/palembang-graphic-system — CC BY 4.0. Generated by the Palembang renderer; see VISUAL-LICENSE.md for scope.</metadata>
  <defs>
    <radialGradient id="sky" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.21929825360599572 -1.9281435999527672 0.9415203344570438 -0.4491017437820297 0.24853804688462697 2.188622625960173)">
      <stop offset="0" stop-color="#DF8117" stop-opacity="1"/>
      <stop offset="1" stop-color="#8198C4" stop-opacity="1"/>
    </radialGradient>
    <radialGradient id="sea-base" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.8099414028954617 -1.8862273661495264 1.8862273661495264 -3.396822741494832 0.3668277375468474 3.6115849804896354)">
      <stop offset="0" stop-color="#8BA08A" stop-opacity="1"/>
      <stop offset="1" stop-color="#516872" stop-opacity="1"/>
    </radialGradient>
    <linearGradient id="sea-haze" gradientUnits="objectBoundingBox" x1="0" y1="0.5" x2="1" y2="0.5" gradientTransform="matrix(-1.5287276299123954e-16 -2.346874889622273 2.346874889622273 -1.6816003929036348e-15 -0.7843749551931998 1.2312499497289566)">
      <stop offset="0.20000000298023224" stop-color="#C0C0C0" stop-opacity="0"/>
      <stop offset="0.30000001192092896" stop-color="#C0C0C0" stop-opacity="0.8"/>
      <stop offset="0.3764832615852356" stop-color="#C0C0C0" stop-opacity="0"/>
    </linearGradient>
    <radialGradient id="sea-glow" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(0.3093751112907292 -1.106250001837 1.106250001837 1.2375004451629168 -0.43281258818896307 0.8249997838079705)">
      <stop offset="0.09071040898561478" stop-color="#78B6BA" stop-opacity="1"/>
      <stop offset="1" stop-color="#78B6BA" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect id="sky-field" x="0" y="0" width="640" height="240" fill="url(#sky)" opacity="1"/>
  <rect id="sea-base-field" x="0" y="240" width="640" height="240" fill="url(#sea-base)" opacity="1"/>
  <rect id="sea-haze-field" x="0" y="240" width="640" height="240" fill="url(#sea-haze)" opacity="0.44999998807907104"/>
  <rect id="sea-glow-field" x="0" y="240" width="640" height="240" fill="url(#sea-glow)" opacity="0.6000000238418579"/>
</svg>
""" + "\n"
        XCTAssertEqual(try Palembang.renderSVG(width: 640, height: 480, hazeMiddleAlpha: 0.8), expected)
    }

    func testExplicitHazeAlpha320Override() throws {
        let expected = """
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="320" height="320" viewBox="0 0 320 320">
  <title>Palembang Graphic System</title>
  <desc>Canonical normalized SVG renderer; haze middle-stop alpha 0.8</desc>
  <metadata>Palembang Graphic System — ybtiger107. https://github.com/ybtiger107/palembang-graphic-system — CC BY 4.0. Generated by the Palembang renderer; see VISUAL-LICENSE.md for scope.</metadata>
  <defs>
    <radialGradient id="sky" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.21929825360599572 -1.9281435999527672 0.9415203344570438 -0.4491017437820297 0.24853804688462697 2.188622625960173)">
      <stop offset="0" stop-color="#DF8117" stop-opacity="1"/>
      <stop offset="1" stop-color="#8198C4" stop-opacity="1"/>
    </radialGradient>
    <radialGradient id="sea-base" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(-0.8099414028954617 -1.8862273661495264 1.8862273661495264 -3.396822741494832 0.3668277375468474 3.6115849804896354)">
      <stop offset="0" stop-color="#8BA08A" stop-opacity="1"/>
      <stop offset="1" stop-color="#516872" stop-opacity="1"/>
    </radialGradient>
    <linearGradient id="sea-haze" gradientUnits="objectBoundingBox" x1="0" y1="0.5" x2="1" y2="0.5" gradientTransform="matrix(-1.5287276299123954e-16 -2.346874889622273 2.346874889622273 -1.6816003929036348e-15 -0.7843749551931998 1.2312499497289566)">
      <stop offset="0.20000000298023224" stop-color="#C0C0C0" stop-opacity="0"/>
      <stop offset="0.30000001192092896" stop-color="#C0C0C0" stop-opacity="0.8"/>
      <stop offset="0.3764832615852356" stop-color="#C0C0C0" stop-opacity="0"/>
    </linearGradient>
    <radialGradient id="sea-glow" gradientUnits="objectBoundingBox" cx="0.5" cy="0.5" r="0.5" gradientTransform="matrix(0.3093751112907292 -1.106250001837 1.106250001837 1.2375004451629168 -0.43281258818896307 0.8249997838079705)">
      <stop offset="0.09071040898561478" stop-color="#78B6BA" stop-opacity="1"/>
      <stop offset="1" stop-color="#78B6BA" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect id="sky-field" x="0" y="0" width="320" height="160" fill="url(#sky)" opacity="1"/>
  <rect id="sea-base-field" x="0" y="160" width="320" height="160" fill="url(#sea-base)" opacity="1"/>
  <rect id="sea-haze-field" x="0" y="160" width="320" height="160" fill="url(#sea-haze)" opacity="0.44999998807907104"/>
  <rect id="sea-glow-field" x="0" y="160" width="320" height="160" fill="url(#sea-glow)" opacity="0.6000000238418579"/>
</svg>
""" + "\n"
        XCTAssertEqual(try Palembang.renderSVG(width: 320, height: 320, hazeMiddleAlpha: 0.8), expected)
    }

    /// Guards the serialization contract the fix above depends on: every
    /// renderer in this repository (render.py, palembang.js, @palembang/core,
    /// and Renderer.swift) terminates its SVG output with a single trailing
    /// LF. This must not regress silently.
    func testRenderedSvgEndsWithTrailingNewline() throws {
        let svg = try Palembang.renderSVG(width: 1920, height: 1080)
        XCTAssertTrue(svg.hasSuffix("\n"))
    }
}
