// Internal SVG assembly. This is a platform port of the same renderer
// contract implemented in implementations/svg/render.py and
// implementations/web/palembang.js: same gradient ids, same layer order
// (sky, sea base, silver haze, teal glow), same inverse-affine transform
// math, same stop/opacity data, same attribution metadata text. It is not a
// new interpretation of Palembang geometry — see docs/implementation-guide.md
// section 4 and packages/swift/README.md.
//
// Nothing in this file is public API; callers only ever see Palembang.swift.
enum Renderer {
    static func renderSVG(
        palette: [String: String],
        width: Double,
        height: Double,
        attribution: Bool,
        hazeMiddleAlpha: Double?
    ) throws -> String {
        let resolvedHazeAlpha: Double
        if let explicit = hazeMiddleAlpha {
            resolvedHazeAlpha = explicit
        } else if width == 320, height == 320 {
            // The 320x320 Figma source exception (docs/specification.md 6.3).
            resolvedHazeAlpha = CanonicalTokens.seaHazeSmall320MiddleStopAlpha
        } else {
            resolvedHazeAlpha = CanonicalTokens.seaHaze.stops[1].alpha
        }

        let halfHeight = height / 2
        let widthText = try SVGNumber.format(width)
        let heightText = try SVGNumber.format(height)
        let halfText = try SVGNumber.format(halfHeight)
        let hazeAlphaText = try SVGNumber.format(resolvedHazeAlpha)

        let sky = try gradientXML(id: "sky", paint: CanonicalTokens.sky, palette: palette)
        let base = try gradientXML(id: "sea-base", paint: CanonicalTokens.seaBase, palette: palette)
        let haze = try gradientXML(
            id: "sea-haze",
            paint: CanonicalTokens.seaHaze,
            palette: palette,
            middleStopAlphaOverride: resolvedHazeAlpha
        )
        let glow = try gradientXML(id: "sea-glow", paint: CanonicalTokens.seaGlow, palette: palette)

        let skyOpacity = try SVGNumber.format(CanonicalTokens.sky.opacity)
        let baseOpacity = try SVGNumber.format(CanonicalTokens.seaBase.opacity)
        let hazeOpacity = try SVGNumber.format(CanonicalTokens.seaHaze.opacity)
        let glowOpacity = try SVGNumber.format(CanonicalTokens.seaGlow.opacity)

        let metadata = attribution
            ? "  <metadata>Palembang Graphic System — ybtiger107. "
                + "https://github.com/ybtiger107/palembang-graphic-system — CC BY 4.0. "
                + "Generated by the Palembang renderer; see VISUAL-LICENSE.md for scope.</metadata>\n"
            : ""

        var svg = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        svg += "<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" "
        svg += "width=\"\(widthText)\" height=\"\(heightText)\" viewBox=\"0 0 \(widthText) \(heightText)\">\n"
        svg += "  <title>Palembang Graphic System</title>\n"
        svg += "  <desc>Canonical normalized SVG renderer; haze middle-stop alpha \(hazeAlphaText)</desc>\n"
        svg += metadata
        svg += "  <defs>\n"
        svg += sky
        svg += base
        svg += haze
        svg += glow
        svg += "  </defs>\n"
        svg += "  <rect id=\"sky-field\" x=\"0\" y=\"0\" width=\"\(widthText)\" height=\"\(halfText)\" "
        svg += "fill=\"url(#sky)\" opacity=\"\(skyOpacity)\"/>\n"
        svg += "  <rect id=\"sea-base-field\" x=\"0\" y=\"\(halfText)\" width=\"\(widthText)\" height=\"\(halfText)\" "
        svg += "fill=\"url(#sea-base)\" opacity=\"\(baseOpacity)\"/>\n"
        svg += "  <rect id=\"sea-haze-field\" x=\"0\" y=\"\(halfText)\" width=\"\(widthText)\" height=\"\(halfText)\" "
        svg += "fill=\"url(#sea-haze)\" opacity=\"\(hazeOpacity)\"/>\n"
        svg += "  <rect id=\"sea-glow-field\" x=\"0\" y=\"\(halfText)\" width=\"\(widthText)\" height=\"\(halfText)\" "
        svg += "fill=\"url(#sea-glow)\" opacity=\"\(glowOpacity)\"/>\n"
        svg += "</svg>\n"
        return svg
    }

    private static func gradientXML(
        id: String,
        paint: GradientPaint,
        palette: [String: String],
        middleStopAlphaOverride: Double? = nil
    ) throws -> String {
        let transform = try svgMatrix(paint.transform)

        var stopsText = ""
        for (index, stop) in paint.stops.enumerated() {
            let alpha = (index == 1 && middleStopAlphaOverride != nil) ? middleStopAlphaOverride! : stop.alpha
            let colorHex = try color(palette, stop.colorToken)
            let offsetText = try SVGNumber.format(stop.position)
            let alphaText = try SVGNumber.format(alpha)
            stopsText += "      <stop offset=\"\(offsetText)\" stop-color=\"\(colorHex)\" stop-opacity=\"\(alphaText)\"/>\n"
        }

        switch paint.kind {
        case .radial:
            let opening = "    <radialGradient id=\"\(id)\" gradientUnits=\"objectBoundingBox\" "
                + "cx=\"0.5\" cy=\"0.5\" r=\"0.5\" gradientTransform=\"\(transform)\">\n"
            return opening + stopsText + "    </radialGradient>\n"
        case .linear:
            let opening = "    <linearGradient id=\"\(id)\" gradientUnits=\"objectBoundingBox\" "
                + "x1=\"0\" y1=\"0.5\" x2=\"1\" y2=\"0.5\" gradientTransform=\"\(transform)\">\n"
            return opening + stopsText + "    </linearGradient>\n"
        }
    }

    private static func color(_ palette: [String: String], _ token: String) throws -> String {
        guard let value = palette[token] else {
            throw PalembangError.renderingFailed("unknown palette token: \(token)")
        }
        return value
    }

    /// Convert a Figma shape->gradient matrix into SVG's gradient->shape
    /// matrix(a b c d e f), identical to render.py's inverse_affine +
    /// svg_matrix and palembang.js's inverseAffine + svgMatrix.
    private static func svgMatrix(_ transform: AffineTransform) throws -> String {
        let values = try inverseAffine(transform)
        let parts = try values.map { try SVGNumber.format($0) }
        return "matrix(\(parts.joined(separator: " ")))"
    }

    private static func inverseAffine(_ t: AffineTransform) throws -> [Double] {
        let a = t.m00, b = t.m01, c = t.m02
        let d = t.m10, e = t.m11, f = t.m12
        let determinant = a * e - b * d
        guard abs(determinant) >= 1e-15 else {
            throw PalembangError.renderingFailed("gradient transform is not invertible")
        }

        let row00 = e / determinant
        let row01 = -b / determinant
        let row02 = (b * f - e * c) / determinant
        let row10 = -d / determinant
        let row11 = a / determinant
        let row12 = (d * c - a * f) / determinant
        // SVG matrix(a b c d e f) maps x'=a*x+c*y+e, y'=b*x+d*y+f.
        return [row00, row10, row01, row11, row02, row12]
    }
}
